# -*- coding: utf-8 -*-
import abjad


performers = abjad.instrumenttools.PerformerList(
    [
        abjad.instrumenttools.Performer(
            name='hornist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.FrenchHorn(
                        instrument_name='horn',
                        short_instrument_name='hn.',
                        instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Horn',),
                            ),
                        short_instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Hn.',),
                            ),
                        allowable_clefs=abjad.datastructuretools.TypedList(
                            [
                                abjad.indicatortools.Clef(
                                    name='bass',
                                    ),
                                abjad.indicatortools.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.pitchtools.PitchRange(
                            range_string='[B1, F5]',
                            ),
                        sounding_pitch_of_written_middle_c=abjad.pitchtools.NamedPitch('f'),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='trombonist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.TenorTrombone(
                        instrument_name='tenor trombone',
                        short_instrument_name='ten. trb.',
                        instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Tenor trombone',),
                            ),
                        short_instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Ten. trb.',),
                            ),
                        allowable_clefs=abjad.datastructuretools.TypedList(
                            [
                                abjad.indicatortools.Clef(
                                    name='tenor',
                                    ),
                                abjad.indicatortools.Clef(
                                    name='bass',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.pitchtools.PitchRange(
                            range_string='[E2, Eb5]',
                            ),
                        sounding_pitch_of_written_middle_c=abjad.pitchtools.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='pianist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Piano(
                        instrument_name='piano',
                        short_instrument_name='pf.',
                        instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Piano',),
                            ),
                        short_instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Pf.',),
                            ),
                        allowable_clefs=abjad.datastructuretools.TypedList(
                            [
                                abjad.indicatortools.Clef(
                                    name='treble',
                                    ),
                                abjad.indicatortools.Clef(
                                    name='bass',
                                    ),
                                ]
                            ),
                        pitch_range=abjad.pitchtools.PitchRange(
                            range_string='[A0, C8]',
                            ),
                        sounding_pitch_of_written_middle_c=abjad.pitchtools.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='percussionist',
            instruments=abjad.instrumenttools.InstrumentList(
                []
                ),
            ),
        abjad.instrumenttools.Performer(
            name='violinist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Violin(
                        instrument_name='violin',
                        short_instrument_name='vn.',
                        instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Violin',),
                            ),
                        short_instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Vn.',),
                            ),
                        allowable_clefs=abjad.datastructuretools.TypedList(
                            [
                                abjad.indicatortools.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        default_tuning=abjad.indicatortools.Tuning(
                            pitches=abjad.pitchtools.PitchSegment(
                                (
                                    abjad.pitchtools.NamedPitch('g'),
                                    abjad.pitchtools.NamedPitch("d'"),
                                    abjad.pitchtools.NamedPitch("a'"),
                                    abjad.pitchtools.NamedPitch("e''"),
                                    ),
                                item_class=abjad.pitchtools.NamedPitch,
                                ),
                            ),
                        pitch_range=abjad.pitchtools.PitchRange(
                            range_string='[G3, G7]',
                            ),
                        sounding_pitch_of_written_middle_c=abjad.pitchtools.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        abjad.instrumenttools.Performer(
            name='cellist',
            instruments=abjad.instrumenttools.InstrumentList(
                [
                    abjad.instrumenttools.Cello(
                        instrument_name='cello',
                        short_instrument_name='vcl.',
                        instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Cello',),
                            ),
                        short_instrument_name_markup=abjad.markuptools.Markup(
                            contents=('Vc.',),
                            ),
                        allowable_clefs=abjad.datastructuretools.TypedList(
                            [
                                abjad.indicatortools.Clef(
                                    name='bass',
                                    ),
                                abjad.indicatortools.Clef(
                                    name='tenor',
                                    ),
                                abjad.indicatortools.Clef(
                                    name='treble',
                                    ),
                                ]
                            ),
                        default_tuning=abjad.indicatortools.Tuning(
                            pitches=abjad.pitchtools.PitchSegment(
                                (
                                    abjad.pitchtools.NamedPitch('c,'),
                                    abjad.pitchtools.NamedPitch('g,'),
                                    abjad.pitchtools.NamedPitch('d'),
                                    abjad.pitchtools.NamedPitch('a'),
                                    ),
                                item_class=abjad.pitchtools.NamedPitch,
                                ),
                            ),
                        pitch_range=abjad.pitchtools.PitchRange(
                            range_string='[C2, G5]',
                            ),
                        sounding_pitch_of_written_middle_c=abjad.pitchtools.NamedPitch("c'"),
                        ),
                    ]
                ),
            ),
        ]
    )
