#! /usr/bin/env python
import sys

import ide

try:
    import readline
    import rlcompleter
    if readline.__doc__ is not None and "libedit" in readline.__doc__:
        readline.parse_and_bind("bind ^I rl_complete")
    else:
        readline.parse_and_bind("tab: complete")
    del readline
    del rlcompleter
except ImportError:
    pass

string = " ".join(sys.argv[1:])
abjad_ide = ide.AbjadIDE()
abjad_ide(string)
