name: ide

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Log environment variables
      run: |
        python --version
        echo $HOME
        echo $GITHUB_WORKSPACE
        echo $PATH

    - name: Install LaTeX add-ons
      run: |
        echo
        echo GRAPHVIZ
        sudo apt-get install graphviz
        echo
        echo IMAGEMAGICK
        sudo apt-get install imagemagick
        # echo
        # echo PGF
        # sudo apt-get install pgf
        echo
        echo TEXLIVE
        sudo apt-get install texlive
        echo
        echo TEXLIVE-EXTRA-UTILS
        sudo apt-get install texlive-extra-utils
        sudo apt-get install texlive-fonts-recommended
        sudo apt-get install texlive-latex-extra
        sudo apt-get install texlive-latex-recommended
        sudo apt-get install texlive-xetex
        # lmodern required for texlive-xetex to find fonts
        echo
        echo LMODERN
        sudo apt-get install lmodern

    - name: Install LilyPond
      run: |
        lilypond_url=http://lilypond.org/download/binaries/linux-64/
        lilypond_source=lilypond-2.23.0-1.linux-64.sh
        wget -q -O /tmp/lilypond $lilypond_url/$lilypond_source
        sh /tmp/lilypond --batch

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Abjad
      run: |
        git clone -b trevor/dev https://github.com/Abjad/abjad.git /tmp/abjad
        pip install -e /tmp/abjad

    - name: Install rmakers
      run: |
        git clone https://github.com/Abjad/abjad-ext-rmakers.git /tmp/abjad-ext-rmakers
        pip install /tmp/abjad-ext-rmakers

    - name: Install this package
      run: |
        python -m pip install -e .

    - name: Install Bača
      run: |
        git clone https://github.com/trevorbaca/baca.git /tmp/baca
        pip install /tmp/baca

    - name: Prime parser tables
      run: /tmp/abjad/scr/prime-parser-tables

    - name: Log versions
      run: |
        export PATH=/home/runner/bin:${PATH}
        black --version
        flake8 --version
        isort --version
        mypy --version
        pip --version
        pytest --version
        lilypond --version

    - name: Run checks
      run: |
        export PATH=/home/runner/bin:${PATH}
        export MYPYPATH=/tmp/abjad:/tmp/abjad-ext-rmakers
        echo $MYPYPATH
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/scores/blue_score
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/scores/red_score
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/scores/green_score
        echo $PYTHONPATH
        make black-check
        make flake8
        make isort-check
        mypy --config-file=$GITHUB_WORKSPACE/mypy.ini ide

    - name: Run tests
      run: |
        export PATH=/home/runner/bin:${PATH}
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/scores/blue_score
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/scores/red_score
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/scores/green_score
        echo $PYTHONPATH
        make pytest
